#!/bin/sh

echo "🧪 Running strict lint checks and type checking before pushing..."
npm run lint:strict || exit 1
# Bỏ qua type-check để không kiểm tra các file test
# npm run type-check || exit 1

exit 0 